### ISSUE TITLE
arc4random 的 libevent 与 glibc 兼容问题

### ISSUE THREAD

**Issue by heroxbd** [Moroshima/zotero-deb#6]
解决方案的参考资料：

1. https://bugs.debian.org/1023284
2. https://github.com/libevent/libevent/issues/1393

**Comment by heroxbd** [comment]
建议：把 libevent 从 firefox 里去掉，让 build 系统使用 OS 中的 libevent 。

**Comment by Moroshima** [comment]
了解，我会立刻着手进行这部分工作的尝试

**Comment by Moroshima** [comment]
成功实现绕过 libevent 该部分编译

**Comment by Moroshima** [comment]
Solution:

```bash
sudo apt install libevent-2.1-7 libevent-core-2.1-7 libevent-extra-2.1-7 libevent-dev
MOZ_SYSTEM_LIBEVENT=1 ./mach build
```

**Comment by heroxbd** [comment]
Moroshima ***@***.***> writes:

> sudo apt install libevent-2.1-7 libevent-core-2.1-7 libevent-extra-2.1-7 libevent-dev
> MOZ_SYSTEM_LIBEVENT=1 ./mach build

太棒了！厉害
